import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
} from 'react-native';
import Svg, {Path} from 'react-native-svg';
import {useNavigation} from '@react-navigation/native';
import {SafeAreaView} from 'react-native-safe-area-context';

const BackIcon = () => (
  <Svg width={24} height={24} viewBox="0 0 24 24" fill="none">
    <Path
      d="M15 19L8 12L15 5"
      stroke="#000"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </Svg>
);

const BulletItem = ({text}: {text: string}) => (
  <View style={styles.bulletRow}>
    <Text style={styles.bullet}>{'•'}</Text>
    <Text style={styles.bulletText}>{text}</Text>
  </View>
);

export default function TermsAndConditionsScreen() {
  const navigation = useNavigation();

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <View style={styles.headerLeft}>
          <TouchableOpacity
            onPress={() => navigation.goBack()}
            style={styles.iconBtn}>
            <BackIcon />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Terms and Conditions</Text>
        </View>
      </View>

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}>
        <Text style={styles.pageTitle}>Terms and Conditions – Parts Now</Text>
        <Text style={styles.pageSubtitle}>
          Governing document for use of the Parts Now Platform
        </Text>

        <Text style={styles.body}>
          This document is an electronic record in terms of the Information
          Technology Act, 2000 and the rules made thereunder, and the amended
          provisions pertaining to electronic records in various statutes as
          amended by the Information Technology Act, 2000. This electronic
          record is generated by a computer system and does not require any
          physical or digital signatures.
        </Text>
        <Text style={styles.body}>
          This document is published in accordance with Rule 3(1) of the
          Information Technology (Intermediary Guidelines and Digital Media
          Ethics Code) Rules, 2021, requiring publication of rules and
          regulations, privacy policy, and terms of use for access or usage of a
          website, mobile site, or mobile application. It governs the access and
          use of the mobile application, website, and backend portal operated
          under the name "Parts Now" ("Platform"), owned and operated by ESOFT
          AUTO PRIVATE LIMITED ("Company", "we", "us", or "our").
        </Text>
        <Text style={styles.body}>
          By accessing, browsing, registering on, or otherwise using the
          Platform, you ("User", "you", or "your") agree to be bound by these
          Terms and Conditions ("Terms of Use" or "Terms"), along with all
          policies referenced here (including the Privacy Policy, Refund/Return
          Policy, Shipping Policy, and any specific product/service terms). If
          you do not agree to these Terms, you must not use the Platform or any
          of the Services.
        </Text>
        <Text style={styles.body}>
          These Terms constitute a legally binding agreement between you and the
          Company for use of the Platform and related services, including access
          to our parts marketplace, ordering services, AI-powered tools,
          workshop dashboards, and garage management software (collectively,
          "Services").
        </Text>
        <Text style={styles.body}>
          The area of jurisdiction for all disputes arising out of or in
          connection with these Terms shall be Indore, Madhya Pradesh, India,
          and these Terms shall be governed by the laws of India.
        </Text>

        <Text style={styles.sectionTitle}>1. Eligibility and Registration</Text>
        <BulletItem text="You must be a natural or legal person competent to contract under the Indian Contract Act, 1872 to use the Platform." />
        <BulletItem text="The Platform is primarily intended for garage and workshop owners and their authorised representatives who procure automotive parts or use workshop management tools." />
        <BulletItem text="When you create an account, you agree to provide true, accurate, current, and complete information (including business name, GSTIN, address, contact details) and keep it updated." />
        <BulletItem text="You are responsible for maintaining the confidentiality of your login credentials and for all activities under your account; any activity from your account will be deemed authorised by you." />
        <BulletItem text="We reserve the right to refuse registration, suspend, or terminate your account at our sole discretion, including for suspected fraud, misrepresentation, or violation of these Terms or applicable law." />

        <Text style={styles.sectionTitle}>2. Scope of Services</Text>
        <Text style={styles.body}>The Platform provides, among other things:</Text>
        <BulletItem text="A B2B spare parts and accessories marketplace connecting workshops with OEMs and authorised distributors for automotive parts and car accessories." />
        <BulletItem text="Negotiated procurement services where we act as an intermediary to obtain competitive pricing and optimal delivery times from our supplier network." />
        <BulletItem text="Doorstep delivery of parts to workshops through in-house and third-party logistics partners." />
        <BulletItem text="AI-powered ordering tools, including voice-based ordering, number-plate-based lookup, image-based part and vehicle detection, and intelligent catalog search." />
        <BulletItem text="A workshop dashboard showing jobs executed, turnaround time, and performance KPIs, and a garage management software for day-to-day operations." />
        <BulletItem text="Digital marketing and promotional services to increase workshop visibility and customer footfall (e.g., ads, online promotions)." />
        <BulletItem text="Services may be updated, modified, or discontinued from time to time at our discretion." />

        <Text style={styles.sectionTitle}>
          3. Platform Access and Acceptable Use
        </Text>
        <Text style={styles.body}>By using the Platform, you agree that you will:</Text>
        <BulletItem text="Use the Platform only for legitimate business purposes related to your workshop or garage operations." />
        <BulletItem text="Not use the Platform for any purpose that is unlawful, illegal, or forbidden by these Terms or by any applicable law or regulation." />
        <BulletItem text="Not attempt to gain unauthorized access to any portion or feature of the Platform, or to any systems or networks connected to the Platform." />
        <BulletItem text="Not engage in activities such as data scraping, reverse engineering, introducing viruses/malware, or any action that may impair the performance or security of the Platform." />
        <BulletItem text="Not upload or transmit any content that is defamatory, obscene, infringing, fraudulent, or otherwise objectionable or illegal." />
        <BulletItem text="Any unauthorised use of the Platform may result in suspension or termination of access and/or legal action." />

        <Text style={styles.sectionTitle}>
          4. Ordering, Pricing, Payments and Delivery
        </Text>

        <Text style={styles.subSectionTitle}>4.1 Orders and Contracts</Text>
        <BulletItem text="When you place an order for parts or services on the Platform, you make a binding offer to purchase those items in accordance with these Terms and the specific product/service terms shown at checkout." />
        <BulletItem text="Order confirmation (via app/website or email/SMS) constitutes acceptance of your offer and forms a binding contract between you and the Company." />

        <Text style={styles.subSectionTitle}>4.2 Pricing and Availability</Text>
        <BulletItem text="Prices, taxes, delivery charges, and applicable fees will be displayed at or before checkout; they may vary by location, supplier, and availability." />
        <BulletItem text="We strive to offer wholesale/distributor-level pricing leveraging our OEM partnerships and distributor network, but final prices remain subject to market conditions and supplier terms." />
        <BulletItem text="Availability of parts and delivery timelines are subject to stock status and logistics constraints; we do not guarantee continuous availability or specific delivery times, though we aim for the fastest possible delivery." />

        <Text style={styles.subSectionTitle}>4.3 Payments</Text>
        <BulletItem text="Payments for orders shall be made through authorized payment methods integrated on the Platform, including Razorpay or other payment aggregators as applicable." />
        <BulletItem text="By initiating a transaction, you authorise the payment gateway and the Company to process your payment in accordance with RBI and payment aggregator guidelines." />
        <BulletItem text="Any payment disputes, chargebacks, or failed transactions will be handled as per the payment gateway and our internal policies; you may be required to provide supporting documentation." />

        <Text style={styles.subSectionTitle}>4.4 Delivery</Text>
        <BulletItem text="Parts will be delivered through a combination of our own logistics and third-party delivery partners, as indicated during checkout." />
        <BulletItem text="Risk of loss passes to you upon delivery of the goods at the address provided by you or upon handover to your authorised representative." />
        <BulletItem text="Delays due to circumstances beyond our control (traffic, weather, supplier delays, force majeure) do not entitle automatic cancellation or compensation, except as provided in our Refund/Return Policy." />

        <Text style={styles.subSectionTitle}>4.5 Returns, Cancellations, and Refunds</Text>
        <BulletItem text="Returns, cancellations, and refunds will be governed by our Refund/Return Policy published on the Platform, which should specify timelines (e.g., within 5–7 working days for approved refunds) and conditions (e.g., unused, in original packaging, non-electrical parts only, etc.)." />
        <BulletItem text="Certain items (e.g., electrical parts, special-order items, customised items) may be non-returnable; such conditions will be indicated wherever reasonably possible." />

        <Text style={styles.sectionTitle}>
          5. Use of AI, Dashboards and Garage Management Software
        </Text>
        <BulletItem text="The Platform includes AI-powered tools (voice ordering, image-based detection, number-plate-based lookup, recommendations) intended to assist in faster and more accurate part identification and ordering." />
        <BulletItem text="These tools rely on available data and algorithms and do not constitute professional advice or a guarantee of suitability or compatibility; you remain responsible for verifying that ordered parts are appropriate for the vehicle and job." />
        <BulletItem text="Workshop dashboards and analytics are provided for informational purposes to help track jobs, turnaround time, and other KPIs; accuracy may depend on the data you input and third-party data sources." />
        <BulletItem text="Garage management features (job tracking, billing, task management, etc.) are offered under a SaaS or subscription model; your use of these features may be subject to specific plan terms, usage limits, and fees displayed on the Platform." />

        <Text style={styles.sectionTitle}>
          6. Subscriptions, SaaS and Value-Added Services
        </Text>
        <BulletItem text="We may offer subscription plans (monthly/annual) that provide access to advanced features, such as detailed analytics dashboards, multi-user access, invoicing tools, priority support, or premium AI insights." />
        <BulletItem text="Plan inclusions, pricing, and billing cycles will be described at the point of subscription; by subscribing, you authorise recurring billing as per the chosen plan until cancelled in accordance with the applicable subscription terms." />
        <BulletItem text="Optional digital marketing services (e.g., online ads, social media promotion, local SEO for workshops) and other value-added services (priority delivery, premium catalog access, partner services) may be offered on a pay-per-use or package basis." />
        <BulletItem text="We may earn commissions from partners (e.g., insurers, financiers, logistics providers) for referrals; details will be provided in relevant service descriptions or partner-specific terms." />

        <Text style={styles.sectionTitle}>7. Third-Party Links and Services</Text>
        <BulletItem text="The Platform may contain links to third-party websites, applications, or services, including payment gateways, logistics providers, marketing platforms, and other partners." />
        <BulletItem text="When you access such third-party services, you may be subject to their separate terms of use, privacy policies, and other policies, which you are responsible for reviewing." />
        <BulletItem text="We do not control, endorse, or assume responsibility for third-party content, products, or services, and your use of them is at your sole risk." />

        <Text style={styles.sectionTitle}>8. Intellectual Property Rights</Text>
        <BulletItem text="All rights, title, and interest in and to the Platform, including but not limited to software, code, AI models, design, layout, look and feel, graphics, logos, trademarks, service marks, text, images, and other content, are owned by or licensed to the Company." />
        <BulletItem text="Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, revocable licence to access and use the Platform and Services solely for your internal business operations as a workshop/garage." />
        <BulletItem text="You shall not reproduce, distribute, modify, create derivative works of, publicly display, or commercially exploit any part of the Platform, except as expressly permitted by us in writing." />
        <BulletItem text="Any feedback, suggestions, or ideas you submit may be used by us to improve the Platform and Services without obligation to compensate you." />

        <Text style={styles.sectionTitle}>9. Data Protection and Privacy</Text>
        <BulletItem text="Our Privacy Policy – Parts Now describes how we collect, use, store, share, and protect personal, business, and technical data, including voice recordings, images, and usage data." />
        <BulletItem text="By using the Platform, you acknowledge and agree that your data will be processed in accordance with the Privacy Policy and applicable data protection laws." />
        <BulletItem text="You are responsible for ensuring that any personal data you provide to us (e.g., customer details entered into the garage management system) has been collected and shared in compliance with applicable law." />

        <Text style={styles.sectionTitle}>10. Charges and Taxes</Text>
        <BulletItem text="You agree to pay all charges associated with availing the Services, including product prices, subscription fees, delivery charges, and any applicable taxes (such as GST) as displayed on the Platform at the time of transaction." />
        <BulletItem text="Prices and fees may be updated from time to time at our discretion, and such changes will apply prospectively from the date of update." />

        <Text style={styles.sectionTitle}>11. Disclaimers</Text>
        <BulletItem text='The Platform and Services are provided on an "as is" and "as available" basis without warranties of any kind, whether express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, or non-infringement.' />
        <BulletItem text="We do not warrant that the Platform will be uninterrupted, timely, secure, or error-free, or that any defects will be corrected." />
        <BulletItem text="We do not guarantee the accuracy, completeness, or suitability of any information, recommendations, or materials provided on the Platform for any specific purpose; you are required to independently assess whether the Services meet your requirements." />
        <BulletItem text="Any reliance you place on such information and materials is strictly at your own risk and discretion." />

        <Text style={styles.sectionTitle}>12. Limitation of Liability</Text>
        <BulletItem text="To the fullest extent permitted by law, in no event shall the Company, its directors, employees, agents, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, business interruption, or loss of data, arising out of or in connection with your use of the Platform or Services." />
        <BulletItem text="Our aggregate liability, whether in contract, tort, or otherwise, for any claims arising out of or relating to these Terms or your use of the Platform shall not exceed the amount paid by you to us for the specific order or subscription giving rise to the claim, or INR 5,000, whichever is lower." />

        <Text style={styles.sectionTitle}>13. Indemnity</Text>
        <Text style={styles.body}>
          You agree to indemnify and hold harmless the Company, its affiliates,
          group companies, and their respective officers, directors, agents, and
          employees from and against any and all claims, demands, actions,
          liabilities, damages, losses, costs, and expenses (including reasonable
          attorneys' fees) arising out of or in connection with:
        </Text>
        <BulletItem text="Your use of the Platform or Services." />
        <BulletItem text="Your breach of these Terms, the Privacy Policy, or any other applicable policies." />
        <BulletItem text="Your violation of any applicable law, regulation, or rights of a third party (including intellectual property rights)." />

        <Text style={styles.sectionTitle}>14. Force Majeure</Text>
        <Text style={styles.body}>
          Notwithstanding anything contained in these Terms, we shall not be
          liable for any failure to perform or delay in performance of any
          obligation where such failure or delay results from events beyond our
          reasonable control, including but not limited to acts of God, natural
          disasters, epidemics, strikes, labour disputes, war, civil disturbance,
          governmental actions, interruption of utilities, or failures of networks
          or communications ("Force Majeure Event").
        </Text>

        <Text style={styles.sectionTitle}>
          15. Modifications to Terms and Services
        </Text>
        <BulletItem text="We reserve the right to modify, update, or replace these Terms (in whole or in part) at any time without prior notice, subject to applicable law." />
        <BulletItem text="It is your responsibility to periodically review the Terms to stay informed of updates; your continued use of the Platform after any modification constitutes your acceptance of the revised Terms." />
        <BulletItem text="We may also modify, suspend, or discontinue any part of the Services with or without notice, without any liability to you." />

        <Text style={styles.sectionTitle}>
          16. Governing Law and Jurisdiction
        </Text>
        <BulletItem text="These Terms, and any dispute or claim relating to them or their enforceability, shall be governed by and construed in accordance with the laws of India." />
        <BulletItem text="All disputes arising out of or in connection with these Terms, the Platform, or the Services shall be subject to the exclusive jurisdiction of the courts at Indore, Madhya Pradesh, India only." />

        <Text style={styles.sectionTitle}>
          17. Grievances and Contact Information
        </Text>
        <Text style={styles.body}>
          For any questions, complaints, or concerns regarding these Terms, the
          Platform, or the Services, you may contact us at:
        </Text>
        <View style={styles.contactBox}>
          <Text style={styles.contactText}>
            <Text style={styles.contactLabel}>Email: </Text>
            esoftauto@gmail.com
          </Text>
          <Text style={styles.contactText}>
            <Text style={styles.contactLabel}>Grievance Officer: </Text>
            Anil Shah
          </Text>
          <Text style={styles.contactText}>
            <Text style={styles.contactLabel}>Company: </Text>
            ESOFT AUTO PRIVATE LIMITED
          </Text>
          <Text style={styles.contactText}>
            <Text style={styles.contactLabel}>Address: </Text>
            Plot no. 420, New Loha Mandi, Scheme no. 78, Phase 2, NIRANJANPUR,
            DEWAS NAKA, INDORE, MADHYA PRADESH 452010, Indore, Madhya Pradesh,
            India
          </Text>
          <Text style={styles.contactNote}>
            We will endeavour to acknowledge and respond to your concerns within
            the time limits prescribed under applicable law.
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: '#fff',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  iconBtn: {
    padding: 4,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#e5383b',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  pageTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
    marginTop: 8,
  },
  pageSubtitle: {
    fontSize: 13,
    color: '#6b7280',
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#111827',
    marginTop: 24,
    marginBottom: 10,
  },
  subSectionTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#374151',
    marginTop: 14,
    marginBottom: 8,
  },
  body: {
    fontSize: 14,
    color: '#374151',
    lineHeight: 22,
    marginBottom: 10,
  },
  bulletRow: {
    flexDirection: 'row',
    marginBottom: 6,
    paddingRight: 4,
  },
  bullet: {
    fontSize: 14,
    color: '#374151',
    marginRight: 8,
    lineHeight: 22,
  },
  bulletText: {
    flex: 1,
    fontSize: 14,
    color: '#374151',
    lineHeight: 22,
  },
  contactBox: {
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 10,
    padding: 16,
    marginTop: 8,
  },
  contactText: {
    fontSize: 14,
    color: '#374151',
    lineHeight: 22,
    marginBottom: 4,
  },
  contactLabel: {
    fontWeight: '600',
  },
  contactNote: {
    fontSize: 13,
    color: '#6b7280',
    marginTop: 8,
    lineHeight: 20,
  },
});
